version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - client/.dev.env
    ports:
      - 5000:5000
    depends_on:
      - backend
    volumes:
      - "./client:/app:delegated"
      - /app/node_modules
    restart: always
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - "./api:/app:delegated"
      - /app/node_modules
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
