version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - 5000:5000
    depends_on:
      - backend
    restart: always
  backend:
    build: ./api
    ports:
      - 3000:3000
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
