FROM node:19-alpine3.16
WORKDIR /app
RUN npm install -g nodemon
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "development-start"]

#docker build -f Dockerfile.dev -t imagename .
#docker run -i -v $(pwd):/app:delegated -v /app/node_modules -p 3000:3000 --name containername imagename