#NAME
name: Push images to Dockerhub and deploy on ELastic Beanstalk
#EVENT
on:
 push:
  branches:
   - master
#JOBS
jobs:
 build_docker_images:
  name: build docker images
  runs-on: [ubuntu-latest]
  steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        logout: true
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker API image
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./api
        push: true
        tags: benspeakman/backend:latest

    - name: Set up environment variables for react Client image
      run: |
        var=$'\nREACT_APP_URL=${{ secrets.REACT_APP_URL }}'; echo "$var" >> client/.env
        
    - name: Build and push Docker Client image
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./client
        push: true
        tags: benspeakman/frontend:latest
        
 deploy_to_elasticbeanstalk:
  name: deploy to elasticbeanstalk
  runs-on: [ubuntu-latest]
  needs: build_docker_images
  steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: cd deploy; zip -r ../deploy.zip .
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
       aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
       aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
       application_name: docker_deploy
       environment_name: docker-deploy-env
       version_label: app-${{ github.sha }}
       existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
       region: eu-west-2
       deployment_package: deploy.zip